# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Fri Apr  8 11:26:09 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(861, 614)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_splitter = QtGui.QSplitter(self.centralwidget)
        self.main_splitter.setFrameShape(QtGui.QFrame.StyledPanel)
        self.main_splitter.setFrameShadow(QtGui.QFrame.Plain)
        self.main_splitter.setLineWidth(2)
        self.main_splitter.setMidLineWidth(2)
        self.main_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.main_splitter.setHandleWidth(10)
        self.main_splitter.setObjectName("main_splitter")
        self.widget_leftpanel = QtGui.QWidget(self.main_splitter)
        self.widget_leftpanel.setMinimumSize(QtCore.QSize(50, 0))
        self.widget_leftpanel.setObjectName("widget_leftpanel")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget_leftpanel)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter_left_layout = QtGui.QVBoxLayout()
        self.splitter_left_layout.setObjectName("splitter_left_layout")
        self.verticalLayout_3.addLayout(self.splitter_left_layout)
        self.widget_right_panel = QtGui.QWidget(self.main_splitter)
        self.widget_right_panel.setObjectName("widget_right_panel")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget_right_panel)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter_right_layout = QtGui.QVBoxLayout()
        self.splitter_right_layout.setContentsMargins(0, 0, 0, 0)
        self.splitter_right_layout.setObjectName("splitter_right_layout")
        self.verticalLayout_2.addLayout(self.splitter_right_layout)
        self.horizontalLayout.addWidget(self.main_splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 861, 25))
        self.menubar.setObjectName("menubar")
        self.menuModel = QtGui.QMenu(self.menubar)
        self.menuModel.setObjectName("menuModel")
        self.menuImport = QtGui.QMenu(self.menubar)
        self.menuImport.setObjectName("menuImport")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.actionSpecifications = QtGui.QAction(MainWindow)
        self.actionSpecifications.setObjectName("actionSpecifications")
        self.actionData_Import = QtGui.QAction(MainWindow)
        self.actionData_Import.setEnabled(True)
        self.actionData_Import.setObjectName("actionData_Import")
        self.actionMaps = QtGui.QAction(MainWindow)
        self.actionMaps.setObjectName("actionMaps")
        self.actionModel = QtGui.QAction(MainWindow)
        self.actionModel.setObjectName("actionModel")
        self.actionTest = QtGui.QAction(MainWindow)
        self.actionTest.setObjectName("actionTest")
        self.actionAuthor = QtGui.QAction(MainWindow)
        self.actionAuthor.setObjectName("actionAuthor")
        self.actionVersion = QtGui.QAction(MainWindow)
        self.actionVersion.setObjectName("actionVersion")
        self.actionImport_Model = QtGui.QAction(MainWindow)
        self.actionImport_Model.setObjectName("actionImport_Model")
        self.menuModel.addAction(self.actionImport_Model)
        self.menuModel.addAction(self.actionSpecifications)
        self.menuModel.addAction(self.actionTest)
        self.menuModel.addSeparator()
        self.menuImport.addAction(self.actionData_Import)
        self.menuAbout.addAction(self.actionAuthor)
        self.menuAbout.addAction(self.actionVersion)
        self.menubar.addAction(self.menuImport.menuAction())
        self.menubar.addAction(self.menuModel.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.menuModel.setTitle(QtGui.QApplication.translate("MainWindow", "Model", None, QtGui.QApplication.UnicodeUTF8))
        self.menuImport.setTitle(QtGui.QApplication.translate("MainWindow", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpecifications.setText(QtGui.QApplication.translate("MainWindow", "Specifications", None, QtGui.QApplication.UnicodeUTF8))
        self.actionData_Import.setText(QtGui.QApplication.translate("MainWindow", "Import...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMaps.setText(QtGui.QApplication.translate("MainWindow", "Maps", None, QtGui.QApplication.UnicodeUTF8))
        self.actionModel.setText(QtGui.QApplication.translate("MainWindow", "Model", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTest.setText(QtGui.QApplication.translate("MainWindow", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAuthor.setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVersion.setText(QtGui.QApplication.translate("MainWindow", "Version", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_Model.setText(QtGui.QApplication.translate("MainWindow", "Import Model", None, QtGui.QApplication.UnicodeUTF8))

